#!/usr/bin/env bash
# Script to install and configure Nginx to serve a custom "Hello World!" page

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
