#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page (plain text only)

# Install Nginx
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo sed -i '/server_name _;/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
