#!/usr/bin/env bash
# This script configures a new Ubuntu server with Nginx and sets a custom HTTP response header "X-Served-By".

# Update and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Configure Nginx to include the custom header
sudo sed -i '/server_name _;/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
sudo systemctl enable nginx
