#!/usr/bin/env bash
# This script configures a new Ubuntu server with Nginx and sets a custom HTTP response header "X-Served-By".

# Update and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Configure Nginx to include the custom header
sudo bash -c 'cat > /etc/nginx/conf.d/custom_header.conf << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        add_header X-Served-By "$hostname";
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
sudo systemctl enable nginx
