#!/usr/bin/env bash
# This script configures the HAProxy load balancer to distribute traffic between web-01 and web-02.

# Update and install HAProxy
sudo apt update -y
sudo apt install -y haproxy

# Configure HAProxy to balance traffic between web-01 and web-02 using roundrobin
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log   local0
    log /dev/log   local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  httplog
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.204.101.142:80 check
    server web-02 100.25.12.114:80 check

EOF'

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
sudo systemctl enable haproxy
