#!/bin/bash

# Get the owner of the file hello
owner=$(stat -c '%U' hello)

# Check if the owner is guillaume
if [ "$owner" = "guillaume" ]
then
    # Change the owner to betty
    chown betty hello
fi
