#!/usr/bin/env bash
# The script ensures Nginx is running and listening on port 80

# Stop Apache if running
pgrep apache2 > /dev/null && sudo pkill apache2

sudo apt update && sudo apt install -y nginx
echo "Hello, World!" | sudo tee /var/www/html/index.html > /dev/null
sudo systemctl restart nginx
curl -s -o /dev/null -w "%{http_code}" http://localhost | grep -q "200" || exit 1