#!/bin/bash
ls -a1 | awk 'BEGIN{ORS=", "} {if($0==".") print "./"; else if($0=="..") print "../"; else {gsub(/ /,"\\ "); if ($0 ~ /^\.|[^/]$/) {print $0} else {print $0 "/"}}}' | sed 's/, $/\n/' | sort -f | awk 'BEGIN{ORS=", "} {print}' | sed 's/, $/\
