#!/usr/bin/env bash
# The script displays a list of currently running processes.

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
awk '{printf "%-10s %-5s %-4s %-4s %-7s %-5s %-8s %-5s %-7s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
