#!/usr/bin/env bash
# The scscript Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

# save scrip pid to /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
# Handle SIGTERM signal by displaying a message
trap 'echo "I hate the kill command"' SIGTERM
# Handle SIGINT signal
trap 'echo "Y U no love me?!"; exit' SIGINT
# Handle SIGQUIT and SIGTERM signals to delete PID file and exit
trap 'rm -f /var/run/myscript.pid; echo "Exiting..."; exit' SIGQUIT SIGTERM

# Display message indefinately
while true
do
	echo "To infinity and beyond"
	sleep 2
done
