#!/usr/bin/env bash
# The script displays The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
	# Extract part of filename after first dash
	name_part=$(echo "$file" | cut -d'-' -f2-)
	echo "$name_part"
done
