#!/usr/bin/env bash
# Bash script that gives you information about the school file.

if [ -e school ]; then
	echo "school file exists"
	
	if [ -s school ]; then  # Check if file empty
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f school ]; then  # Check if file is regular file
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
