#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

if [ "$(id -u)" -ne 0 ]; then
	echo " Please run as root with sudo."
	exit 1
fi

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

sed -i '/127.0.0.2 localhost/d' /etc/hosts
sed -i '/8.8.8.8 facebook.com/d' /etc/hosts

# Append the new entries
echo "127.0.0.2 mylocalhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | tee -a /etc/hosts
