#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# Check commands available
if command -v ifconfig &> /dev/null; then
	ifconfig | grep 'inet ' | awk '{print $2}'
elif command -v ip &> /dev/null; then
	ip addr | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1
else
	echo "No active IPv4 IPs command available"
	exit 1
fi
