#!/usr/bin/env bash
# Bash script that listens on port 98 on localhost.
# Check if user is root
if [ "$(id -u)" -ne 0 ]; then
	echo "Please run as root."
	exit 1
fi
# Use of Netcat to listen on port 98 on localhost
nc -l -p 98 -s 127.0.0.1 -k
