#!/usr/bin/env bash
# Fix Nginx to run as nginx user and listen on port 8080

sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx
service nginx restart